# coding: utf-8

"""
    fn

    The open source serverless platform.

    OpenAPI spec version: 0.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.call_api import CallApi


class TestCallApi(unittest.TestCase):
    """ CallApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.call_api.CallApi()

    def tearDown(self):
        pass

    def test_apps_app_calls_call_get(self):
        """
        Test case for apps_app_calls_call_get

        Get call information
        """
        pass

    def test_apps_app_calls_call_log_delete(self):
        """
        Test case for apps_app_calls_call_log_delete

        Delete call log entry
        """
        pass

    def test_apps_app_calls_call_log_get(self):
        """
        Test case for apps_app_calls_call_log_get

        Get call logs
        """
        pass

    def test_apps_app_calls_get(self):
        """
        Test case for apps_app_calls_get

        Get app-bound calls.
        """
        pass


if __name__ == '__main__':
    unittest.main()
