# coding: utf-8

"""
    fn

    The open source serverless platform.

    OpenAPI spec version: 0.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.routes_api import RoutesApi


class TestRoutesApi(unittest.TestCase):
    """ RoutesApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.routes_api.RoutesApi()

    def tearDown(self):
        pass

    def test_apps_app_routes_get(self):
        """
        Test case for apps_app_routes_get

        Get route list by app name.
        """
        pass

    def test_apps_app_routes_post(self):
        """
        Test case for apps_app_routes_post

        Create new Route
        """
        pass

    def test_apps_app_routes_route_delete(self):
        """
        Test case for apps_app_routes_route_delete

        Deletes the route
        """
        pass

    def test_apps_app_routes_route_get(self):
        """
        Test case for apps_app_routes_route_get

        Gets route by name
        """
        pass

    def test_apps_app_routes_route_patch(self):
        """
        Test case for apps_app_routes_route_patch

        Update a Route, Fails if the route or app does not exist. Accepts partial updates / skips validation of zero values.
        """
        pass

    def test_apps_app_routes_route_put(self):
        """
        Test case for apps_app_routes_route_put

        Create a Route if it does not exist. Update if it does. Will also create app if it does not exist. Put does not skip validation of zero values
        """
        pass


if __name__ == '__main__':
    unittest.main()
