# coding: utf-8

"""
    IronFunctions

    The open source serverless platform.

    OpenAPI spec version: 0.1.29
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.tasks_api import TasksApi


class TestTasksApi(unittest.TestCase):
    """ TasksApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.tasks_api.TasksApi()

    def tearDown(self):
        pass

    def test_tasks_get(self):
        """
        Test case for tasks_get

        Get next task.
        """
        pass


if __name__ == '__main__':
    unittest.main()
