# coding: utf-8

"""
    fn

    The open source serverless platform.

    OpenAPI spec version: 0.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.call_wrapper import CallWrapper


class TestCallWrapper(unittest.TestCase):
    """ CallWrapper unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallWrapper(self):
        """
        Test CallWrapper
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.call_wrapper.CallWrapper()
        pass


if __name__ == '__main__':
    unittest.main()
