# coding: utf-8

"""
    IronFunctions

    The open source serverless platform.

    OpenAPI spec version: 0.1.29
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.version_api import VersionApi


class TestVersionApi(unittest.TestCase):
    """ VersionApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.version_api.VersionApi()

    def tearDown(self):
        pass

    def test_version_get(self):
        """
        Test case for version_get

        Get daemon version.
        """
        pass


if __name__ == '__main__':
    unittest.main()
