# coding: utf-8

"""
    IronFunctions

    The open source serverless platform.

    OpenAPI spec version: 0.1.29
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.task_wrapper import TaskWrapper


class TestTaskWrapper(unittest.TestCase):
    """ TaskWrapper unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTaskWrapper(self):
        """
        Test TaskWrapper
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.task_wrapper.TaskWrapper()
        pass


if __name__ == '__main__':
    unittest.main()
