# coding: utf-8

"""
    fn

    The open source serverless platform.

    OpenAPI spec version: 0.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.calls_wrapper import CallsWrapper


class TestCallsWrapper(unittest.TestCase):
    """ CallsWrapper unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCallsWrapper(self):
        """
        Test CallsWrapper
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.calls_wrapper.CallsWrapper()
        pass


if __name__ == '__main__':
    unittest.main()
