# coding: utf-8

"""
    IronFunctions

    The open source serverless platform.

    OpenAPI spec version: 0.1.29
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.apps_api import AppsApi


class TestAppsApi(unittest.TestCase):
    """ AppsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.apps_api.AppsApi()

    def tearDown(self):
        pass

    def test_apps_app_delete(self):
        """
        Test case for apps_app_delete

        Delete an app.
        """
        pass

    def test_apps_app_get(self):
        """
        Test case for apps_app_get

        Get information for a app.
        """
        pass

    def test_apps_app_patch(self):
        """
        Test case for apps_app_patch

        Updates an app.
        """
        pass

    def test_apps_get(self):
        """
        Test case for apps_get

        Get all app names.
        """
        pass

    def test_apps_post(self):
        """
        Test case for apps_post

        Post new app
        """
        pass


if __name__ == '__main__':
    unittest.main()
