# coding: utf-8

"""
    fn

    The open source serverless platform.

    OpenAPI spec version: 0.2.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RoutesWrapper(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'next_cursor': 'str',
        'routes': 'list[Route]',
        'error': 'ErrorBody'
    }

    attribute_map = {
        'next_cursor': 'next_cursor',
        'routes': 'routes',
        'error': 'error'
    }

    def __init__(self, next_cursor=None, routes=None, error=None):
        """
        RoutesWrapper - a model defined in Swagger
        """

        self._next_cursor = None
        self._routes = None
        self._error = None

        if next_cursor is not None:
          self.next_cursor = next_cursor
        self.routes = routes
        if error is not None:
          self.error = error

    @property
    def next_cursor(self):
        """
        Gets the next_cursor of this RoutesWrapper.
        cursor to send with subsequent request to receive the next page, if non-empty

        :return: The next_cursor of this RoutesWrapper.
        :rtype: str
        """
        return self._next_cursor

    @next_cursor.setter
    def next_cursor(self, next_cursor):
        """
        Sets the next_cursor of this RoutesWrapper.
        cursor to send with subsequent request to receive the next page, if non-empty

        :param next_cursor: The next_cursor of this RoutesWrapper.
        :type: str
        """

        self._next_cursor = next_cursor

    @property
    def routes(self):
        """
        Gets the routes of this RoutesWrapper.

        :return: The routes of this RoutesWrapper.
        :rtype: list[Route]
        """
        return self._routes

    @routes.setter
    def routes(self, routes):
        """
        Sets the routes of this RoutesWrapper.

        :param routes: The routes of this RoutesWrapper.
        :type: list[Route]
        """
        if routes is None:
            raise ValueError("Invalid value for `routes`, must not be `None`")

        self._routes = routes

    @property
    def error(self):
        """
        Gets the error of this RoutesWrapper.

        :return: The error of this RoutesWrapper.
        :rtype: ErrorBody
        """
        return self._error

    @error.setter
    def error(self, error):
        """
        Sets the error of this RoutesWrapper.

        :param error: The error of this RoutesWrapper.
        :type: ErrorBody
        """

        self._error = error

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RoutesWrapper):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
