# coding: utf-8

"""
    IronFunctions

    The open source serverless platform.

    OpenAPI spec version: 0.1.29
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RouteWrapper(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'message': 'str',
        'error': 'ErrorBody',
        'route': 'Route'
    }

    attribute_map = {
        'message': 'message',
        'error': 'error',
        'route': 'route'
    }

    def __init__(self, message=None, error=None, route=None):
        """
        RouteWrapper - a model defined in Swagger
        """

        self._message = None
        self._error = None
        self._route = None

        if message is not None:
          self.message = message
        if error is not None:
          self.error = error
        self.route = route

    @property
    def message(self):
        """
        Gets the message of this RouteWrapper.

        :return: The message of this RouteWrapper.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message):
        """
        Sets the message of this RouteWrapper.

        :param message: The message of this RouteWrapper.
        :type: str
        """

        self._message = message

    @property
    def error(self):
        """
        Gets the error of this RouteWrapper.

        :return: The error of this RouteWrapper.
        :rtype: ErrorBody
        """
        return self._error

    @error.setter
    def error(self, error):
        """
        Sets the error of this RouteWrapper.

        :param error: The error of this RouteWrapper.
        :type: ErrorBody
        """

        self._error = error

    @property
    def route(self):
        """
        Gets the route of this RouteWrapper.

        :return: The route of this RouteWrapper.
        :rtype: Route
        """
        return self._route

    @route.setter
    def route(self, route):
        """
        Sets the route of this RouteWrapper.

        :param route: The route of this RouteWrapper.
        :type: Route
        """
        if route is None:
            raise ValueError("Invalid value for `route`, must not be `None`")

        self._route = route

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RouteWrapper):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
